### ISSUE TITLE
Support GitHub enterprise as a build definition repository type

### ISSUE THREAD

**Issue by EliiseS** [xuzhang3/terraform-provider-azuredevops#35]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/218
Originally created by @cwebbtw on *Fri, 06 Dec 2019 17:16:37 GMT*

---
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The currently supported repository types for the `azuredevops_build_definition` are GitHub and TfsGit.

As a user of github enterprise, I would like to be able to build a pipeline definition using infrastructure as code so that I can repeatedly build in the same way for multiple teams.

### New or Affected Resource(s)

**resource**: azuredevops_build_definition

### Potential Terraform Configuration

```hcl
resource "azuredevops_build_definition" "build" {
  project_id = azuredevops_project.project.id
  name       = "Sample Build Definition"
  path       = "\\ExampleFolder"

  repository {
    repo_type   = "GitHubEnterprise"
    personal_access_token = "..."
    repo_name   = azuredevops_azure_git_repository.repository.name
    branch_name = azuredevops_azure_git_repository.repository.default_branch
    yml_path    = "azure-pipelines.yml"
  }
}
```

* #0000

**Comment by xuzhang3** [comment]
Close this issue. Free free to reopen it if anyone have questions.
